name = "VASPseudopotentials"
uuid = "a8aa8eba-0278-4e3a-8f77-14d2f4143e9c"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
